# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '10.0'
inhibit_all_warnings!

target 'OrderSummary' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!

    # Pods for OrderSummary
       pod 'Alamofire'
       pod 'AlamofireImage'
       pod 'SwiftyJSON', '~> 4.0'
       pod 'SwiftIcons'
end

post_install do |lib|
    lib.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        end
    end
end
